### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by pupnewfster** [Tfarcenim/Toughness-Bar#1]
I decided to see how this would look like in game but got a crash on loading. Looking at the uploaded jar it seems like you uploaded the wrong one or something.
Inside the jar, the folder structure is:
`toughnessbar-1.1/`
And inside that folder:
```
.idea/
assets/
com/
META-INF/
mcmod.info
pack.mcmeta
```
The `.idea/` folder shouldn't be there, and all the other folders should be up one level.

Version: 1.2
https://paste.dimdev.org/iceyeraray.mccrash

**Comment by Tfarcenim** [comment]
oops, there was an issue with 1.0 to 1.2 that it wasn't building correctly because I forgot to run clean.  So outside of the dev environment it would crash.
