### ISSUE TITLE
Crash!

### ISSUE THREAD

**Issue by Chancho91** [Tfarcenim/Toughness-Bar#12]
Here is the crash report.
[crash-2020-12-17_13.04.00-fml.txt](https://github.com/Tfarcenim/Toughness-Bar/files/5711312/crash-2020-12-17_13.04.00-fml.txt)

**Comment by choekstr** [comment]
Coincidentally just came here to report this as well.  Direwolf 1.16.4 pack and I assume this was compiled for just 1.16.0.  Doesn't seem to work on 1.16.4.

There isn't a dependency section in the mods.toml file which is typically required to ensure it can't be run on an unsupported version of MC.
