### ISSUE TITLE
Crash issue with Hwyla??? (Project Ozone 3)

### ISSUE THREAD

**Issue by Leo40Git** [Tfarcenim/Toughness-Bar#4]
uhh??? i have no idea

crash log: https://pastebin.com/CSEzfZfH

using PO3 v3.0.38 with toughness bar v2.1 added

**Comment by Leo40Git** [comment]
issue on Wawla's repo: https://github.com/Darkhax-Minecraft/WAWLA/issues/107

**Comment by Tfarcenim** [comment]
I've got no idea what's going on here but I was unable to reproduce it.
