### ISSUE TITLE
[Suggestion] Config option to disable the Bedrock layer.

### ISSUE THREAD

**Issue by SonicX8000** [Tfarcenim/Toughness-Bar#5]
The Bedrock layer is used if you go above the last layer color. Could there be an option to disable this and instead have it loop on the last layer color? Like...

If enabled: red -> yellow -> green -> bedrock -> bedrock

If disabled: red -> yellow -> green -> green -> green

By the way... the Bedrock layer is bug'd where it uses the first colored layer.
![](https://cdn.discordapp.com/attachments/377171551155650560/569194442699964453/bedrocklayerdiscolor.PNG)

**Comment by Tfarcenim** [comment]
done
