### ISSUE TITLE
Underwater bubbles on hotbar causes held item tooltip to overlap

### ISSUE THREAD

**Issue by IronPiston** [Tfarcenim/Toughness-Bar#8]
Having any toughness icons in addition to being underwater causes the item name to render over the bubbles. Could being underwater force this tooltip up to avoid this?
![2019-07-13_15 56 49](https://user-images.githubusercontent.com/11603684/61176465-e81e2080-a586-11e9-8249-4822bbb19472.png)

**Comment by Tfarcenim** [comment]
It doesn't do that with just toughness bar installed, so you've got a (core)mod breaking rendering somewhere

**Comment by IronPiston** [comment]
Tried again with only toughness bar installed, still running into the same issue
Forge: 14.23.5.2847
Toughness bar(1.12): 2.3

![2019-10-12_21 15 06](https://user-images.githubusercontent.com/11603684/66710007-64b2cd80-ed35-11e9-8b55-78cb23bffbf3.png)

**Comment by SonicX8000** [comment]
@IronPiston 
This also occurs if you have Armor & Absorb. Using only Forge so might be a vanilla thing.

![](https://cdn.discordapp.com/attachments/377171551155650560/639231357956128800/textoverlap.PNG)

If you want a workaround, there's a mod called "Console Experience" which allows you to move the Tooltip around.

**Comment by CCCClear** [comment]
I have some suggestions on this, if you can add a config to adjust the position of the toughness bar, because I want it to appear above the armor bar and not the hunger bar.

**Comment by Tfarcenim** [comment]
> I have some suggestions on this, if you can add a config to adjust the position of the toughness bar, because I want it to appear above the armor bar and not the hunger bar.

This needs to be a new issue

As for this one, it's a vanilla issue that can be triggered in vanilla, not the fault of this mod.
